dataset_path: "./dataset"

checkpoint_dir: .ckpts
seed: 12405

simplekt_config:
  embedding_size: 64
  num_blocks: 2
  num_attn_heads: 8
  dropout: 0.5

routersimplekt_config:
  embedding_size: 64
  num_blocks: 2
  num_attn_heads: 8
  dropout: 0.5
  num_shared_heads: 2
  num_selected_heads: 4
  num_alibi_heads: 0
  balance_loss_weight: 0.01

akt_config:
  embedding_size: 64
  num_blocks: 2
  kq_same: True
  model_type: "akt"
  num_attn_heads: 8
  final_fc_dim: 512
  d_ff: 1024
  l2: 0.1
  dropout: 0.05
  separate_qr: False
  num_shared_heads: 2

routerakt_config:
  algebra05:
    l2: 0.0001
    balance_loss_weight: 0.001
    num_selected_heads: 2
    num_shared_heads: 2
    routing_mode: "dynamic"
    embedding_size: 64
    num_blocks: 2
    kq_same: True
    model_type: "routerakt"
    num_attn_heads: 8
    final_fc_dim: 512
    d_ff: 1024
    dropout: 0.05
    separate_qr: False

  bridge06:
    l2: 0.0
    balance_loss_weight: 0.001
    num_selected_heads: 1
    num_shared_heads: 2
    routing_mode: "dynamic"
    embedding_size: 64
    num_blocks: 2
    kq_same: True
    model_type: "routerakt"
    num_attn_heads: 8
    final_fc_dim: 512
    d_ff: 1024
    dropout: 0.05
    separate_qr: False
  
  assistments09:
    l2: 0.0001
    balance_loss_weight: 0.0
    num_selected_heads: 4
    num_shared_heads: 1
    routing_mode: "dynamic"
    embedding_size: 64
    num_blocks: 2
    kq_same: True
    model_type: "routerakt"
    num_attn_heads: 8
    final_fc_dim: 512
    d_ff: 1024
    dropout: 0.05
    separate_qr: False

  ednet:
    l2: 0.0
    balance_loss_weight: 0.001
    num_selected_heads: 2
    num_shared_heads: 1
    routing_mode: "dynamic"
    embedding_size: 64
    num_blocks: 2
    kq_same: True
    model_type: "routerakt"
    num_attn_heads: 8
    final_fc_dim: 512
    d_ff: 1024
    dropout: 0.05
    separate_qr: False
  
  slepemapy:
    l2: 0.1
    balance_loss_weight: 0.01
    num_selected_heads: 4
    num_shared_heads: 1
    routing_mode: "dynamic"
    embedding_size: 64
    num_blocks: 2
    kq_same: True
    model_type: "routerakt"
    num_attn_heads: 8
    final_fc_dim: 512
    d_ff: 1024
    dropout: 0.05
    separate_qr: False
  linux:
    l2: 0.1
    balance_loss_weight: 0.01
    num_selected_heads: 4
    num_shared_heads: 1
    routing_mode: "dynamic"
    embedding_size: 64
    num_blocks: 2
    kq_same: True
    model_type: "routerakt"
    num_attn_heads: 8
    final_fc_dim: 512
    d_ff: 1024
    dropout: 0.05
    separate_qr: False
  database:
    l2: 0.1
    balance_loss_weight: 0.0
    num_selected_heads: 4
    num_shared_heads: 1
    routing_mode: "dynamic"
    embedding_size: 64
    num_blocks: 2
    kq_same: True
    model_type: "routerakt"
    num_attn_heads: 8
    final_fc_dim: 512
    d_ff: 1024
    dropout: 0.05
    separate_qr: False

cl4kt_config:
  hidden_size: 64
  num_blocks: 2
  num_attn_heads: 8
  kq_same: True
  final_fc_dim: 512
  d_ff: 1024
  l2: 0.0
  dropout: 0.2
  reg_cl: 0.1
  mask_prob: 0.2
  crop_prob: 0.3
  permute_prob: 0.3
  replace_prob: 0.3
  negative_prob: 1.0
  temp: 0.05
  hard_negative_weight: 1.0

routercl4kt_config:
  hidden_size: 64
  num_blocks: 2
  num_attn_heads: 8
  num_shared_heads: 2
  num_selected_heads: 4
  kq_same: True
  final_fc_dim: 512
  d_ff: 1024
  l2: 0.0
  dropout: 0.2
  reg_cl: 0.1
  mask_prob: 0.2
  crop_prob: 0.3
  permute_prob: 0.3
  replace_prob: 0.3
  negative_prob: 1.0
  temp: 0.05
  hard_negative_weight: 1.0
  routing_mode: "query_norm"
  balance_loss_weight: 0.001

train_config:
  l2: 0.0
  log_wandb_fold: True
  sequence_option: "recent" # early or recent
  seq_len: 100
  batch_size: 512
  eval_batch_size: 512
  #num_epochs: 1
  num_epochs: 300
  print_epochs: 1
  max_grad_norm: 2.0
  learning_rate: 0.001
  optimizer: adam
  diff_order: "random"

  loss: BCE

  ## Model Save
  save_model: False
  save_epochs: 1
  save_model_name: "tmp"
  log_path: "logs"
